version: "3"

services:
  app:
    image: linuxserver/plex:1.41.2
    network_mode: host
    environment:
      - TZ="Europe/Berlin"
    volumes:
      - config:/config
      - transcode:/transcode
    restart: unless-stopped

volumes:
  config:
  transcode:
