---
version: "3"
services:
  app:
    image: linuxserver/plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
    volumes:
      - config:/config
      - transcode:/transcode
    restart: unless-stopped

volumes:
  config:
  transcode:
